### ISSUE TITLE
Issue with uploading a profile picture

### ISSUE THREAD

**Issue by DanielLvovsky** [20chix/ziplinks#23]
Hi there,

So I am having issues with uploading a profile pic, I have setup my own firebase database but it seems that the profile pic is not uploading. Is that an issue that happened in the past or is this something new? Any help is appreciated

Thanks, 
Daniel

**Comment by DanielLvovsky** [comment]
I forgot to mention that the error code is : "storage/object-not-found"

**Comment by 20chix** [comment]
Hi,

In order to save storage space I use a firebase extension called `resize image` which resize the image that user uploads to a thumbnail 200x200.

At the moment there isn't any callback that tells me when the image is been resized. The only work around for now(I think) is to upload the image wait couple of second until the image is been resized then get the image URL from storage, if is not found then do another query to get the image URL.

Any suggestions?

**Comment by DanielLvovsky** [comment]
This is not related to the issue raised above but is this deployed on Heroku? since I tried testing it on Netlify and the user URL does not work.

**Comment by 20chix** [comment]
> This is not related to the issue raised above but is this deployed on Heroku? since I tried testing it on Netlify and the user URL does not work.

Nope, deployed in firebase, I'll update the Readme with more info about the deployment and extension

**Comment by DanielLvovsky** [comment]
Thank you for your help.

**Comment by DanielLvovsky** [comment]
I have figured out how to deploy it now. Just mention how to use the firebase cli in order to deploy.

**Comment by 20chix** [comment]
Added 👍
